### PR TITLE
Fix updating plugins with ver-ice

### PR DESCRIPTION
**Pull request by NICHOLAS85**
Use `git merge` when ver ice is present, to merge any updates. Replace `git pull --recurse-submodules` with `git submodule update --init --recursive` to only update submodules and not undo the previous fix. Add an "Already up to date." message, previously provided by the `git pull --recurse-submodules` command, if the plugin is up to date.

This fixes issue #210, let me know what you think!

### CODE REVIEW

**Comment by NICHOLAS85** [comment]
I've implemented a fix for gh-releases. One small problem is that repos which use a tag to build nightly builds, will not download updates as the following line is not specific enough to indicate the release currently downloaded is different from the one upstream.
https://github.com/zdharma/zplugin/blob/855f11259a03d286685bc21901cf03efb932be5e/zplugin-install.zsh#L901

For example using:
```
zplugin ice from"gh-r" ver'nightly' bpick'*linux64*'
zplugin zyedidia/micro
```
Will make the following line always true </br> `/zyedidia/micro/releases/download/nightly/micro-1.4.2-dev.77-linux64.tar.gz = */nightly/*`:
https://github.com/zdharma/zplugin/blob/60094e8fb54eff1680419433a5de782ec11a9e9c/zplugin-autoload.zsh#L1385
Is there a way $REPLY could be more specific? It looks like the file name itself could be added and also used to match.

**Comment by psprint** [comment]
Thanks, I'll dig into the PR soon, but right now could you take a look at #164 referring to the submodule updating?

**Comment by NICHOLAS85** [comment]
In order to not update the plugin past the ver-ice specified the original command had to be replaced. I believe `git submodule update --init --recursive` should be an equivalent replacement for `git pull --recurse-submodules` as you already pull/merge changes prior to this point. It won't pull submodules which do not need to be updated past the point at which they exist in the cloned repo unless `--remote` is supplied. So the problem that occurred in #164 shouldn't happen. I've done some testing and haven't run into any issue but I'll keep poking at it.

**Comment by psprint** [comment]
OK, I've merged. I've only added condition on `ver` for using the new `git` command. I'm not fully following the reasons of #164 so I've done this. Now for the proposed `$REPLY` update then I think that yes, it's possible to extend it, I'll take a look or maybe you could.

**Comment by psprint** [comment]
I'm sorry but I've had to revert. Noticed problems:
- git log to `ver` isn't going to work – it'll do just that, show commits from current version to current version,
- the check on the merge/pull git subcommand was using `ZPLG_ICE`, while it should be using `ice`
- the commits caused a duplicate message about up to date repo.

**Comment by NICHOLAS85** [comment]
Understandable! I've made a draft pull request #217 with some discussion on the reasons for certain code changes and responses to your concerns. There we can figure out a better solution!

**Pull request merged**
