### PR TITLE
Make the "News" section of the README collapsible

### PR DESCRIPTION
**Pull request by RobertAudi**
Move the "New" section inside a `<details>` HTML tag so that it can be collapsed.

### CODE REVIEW

**Comment by psprint** [comment]
I like the change, however after applying it, the link to the changelog renders unprocessed:

collapsable-news-section

**Comment by DundarGoc** [comment]
It works with html, that is:

```
<summary>
Here are the new features and updates added to zplugin in the last 90 days. To see the full history check <a href="CHANGELOG.md">the changelog</a>
</summary>
```

**Comment by RobertAudi** [comment]
@psprint You are correct. The only solution I found (it's a compromise really) is to move the link to the Changelog below the collapsible section.

Another solution would be to add the link in the summary as HTML instead of markdown.

**Comment by DundarGoc** [comment]
I'm conflicted with hiding away the News section. It feels a bit counterproductive hiding away information we want to announce. Another approach could be to limit the news to the past 30 days or the last 5 changes instead maybe?

**Comment by RobertAudi** [comment]
The collapsed section can be shown with a single click without leaving the page. 🤔

**Comment by DundarGoc** [comment]
Eh, you're right, I'm nitpicking at this point.

**Comment by RobertAudi** [comment]
@psprint I fixed the problem with the link to the CHANGELOG in the README. Tell me if you would like me to perform any other changes :slightly_smiling_face:

**Comment by psprint** [comment]
No, no other changes are needed, thanks!

**Pull request merged**
