### PR TITLE
Fixed P10K example with `compile` ice

### PR DESCRIPTION
**Pull request by robobenklein**
From discussion following #92

### CODE REVIEW

**Comment by psprint** [comment]
I've missed this PR. Should I still merge it? It does look fine (the zplugin invocation). However, I've just noticed that Zplugin doesn't load p10k correctly:

```zsh
% zplg load robobenklein/p10k
Compiling p10k.zsh-theme...
--zplg-shadow-autoload:19: prompt_p10k_setup: function definition file not found
zsh: prompt_p10k_setup: function definition file not found
p10k_selfdestruct_setup:17: command not found: prompt_p10k_preexec
p10k_selfdestruct_setup:18: command not found: prompt_p10k_precmd
```

Do you maybe observe the same behavior?

**Comment by robobenklein** [comment]
I suspect there's another issue with the fpath interactions, thanks for letting me know, but I'm not sure what to do to reproduce.

**Comment by robobenklein** [comment]
Well I have a few things to fix that include using `-` instead of `_` for my private use functions so they don't get picked up as completions...

I think these fpath issues are zplugin specific since this is the only plugin manager that I've seen the behaviour in. My original workaround is to do loading of P10K mostly in the precmd hook to load right before the first prompt, but perhaps there's another issue there.

**Comment by robobenklein** [comment]
I will open a new one when I am done renaming P10K.

**Pull request closed without merging**
