### PR TITLE
Fix light mode in `for`-syntax

### PR DESCRIPTION
**Pull request by NICHOLAS85**
Line 1894 was returning load regardless of if `ZPLG_ICE[light]` was set or not. It seemed the `:#1` portion was matching every time and setting it null from my tests.

I replaced the line with `"${${(M)+ZPLG_ICE[light]+light}:-load}" \` and it seems to work correctly now. Although I am not completely familiar with zsh and the differences between what you were attempting to do and my quick fix.

### CODE REVIEW

**Comment by psprint** [comment]
Looking at the code, it seems to be correct. It also seems to work: https://asciinema.org/a/IDnnD4fegOcxz6Pg5P9Pg2EDH. Could you record a similar video showing how the feature doesn't seem to work?

**Comment by psprint** [comment]
Well, no, the code isn't correct, because the `+` is being applied after the `:#` substitution. I'll merge the PR, but could you remove the `(M)`? It isn't needed.

**Comment by NICHOLAS85** [comment]
Removed the `(M)`.

`${(M)+ZPLG_ICE[light]:#1}` was always empty regardless of if `+ZPLG_ICE[light]` returned 1 or 0. It ended up forcing all the plugins to load instead of respecting their light ice.

**Comment by psprint** [comment]
Thanks!

**Comment by psprint** [comment]
Yeah, when I wrote "the code seems to be correct" and then "No …" I was referring to the original code, i.e.: mine.

**Comment by psprint** [comment]
BTW. I've just renamed the ice to `light-mode` to prevent clashes with the subcommand.

**Pull request merged**
