### PR TITLE
${~ZPFX}/bin should be added to PATH only once

### PR DESCRIPTION
**Pull request by agkozak**
As it is right now, `${~ZPFX}/bin` gets added to `PATH` even when it's already there, which can lead to `PATH`s such as

    /home/alexandros/.zplugin/polaris/bin:/home/alexandros/.zplugin/polaris/bin:/home/alexandros/.zplugin/polaris/bin:/home/alexandros/.zplugin/polaris/bin:/home/alexandros/perl5/bin:/home/alexandros/bin:/home/alexandros/.luarocks/bin:/home/alexandros/.config/composer/vendor/bin:/home/alexandros/.cabal/bin:/home/alexandros/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin

This pull request fixes the problem by checking to see if `${~ZPFX}/bin` is an element of the array `path` before adding it to `path`.

### CODE REVIEW

**Comment by agkozak** [comment]
I should check this against `KSH_ARRAYS` and `SH_WORD_SPLIT`.

**Comment by psprint** [comment]
This reveals one other problem with the KSH: the index returned by `(i)` will be one less than the array size when KSH is on. So I think that the test should be:

```zsh
 [[ -n ${path[(re)$ZPFX/bin]} ]] || path=( "$ZPFX/bin" ${path[@]} )
```

So I also think that the `~` could be skipped as the previous line already does the substitution. This opens the way to quote the expression (it would block the `~` substitution) and protect against SH.

**Comment by agkozak** [comment]
Got it. Thanks, @psprint!

**Comment by psprint** [comment]
It's merged, thanks!

**Pull request merged**
