### PR TITLE
zplugin: Process trigger-load ice before others

### PR DESCRIPTION
**Pull request by NICHOLAS85**
For: https://github.com/zdharma/zplugin/pull/202#issuecomment-551271791

### CODE REVIEW

**Comment by psprint** [comment]
Thanks! Could you move the `id-as"auto"` processing back? This one should be processed where it was.

**Comment by NICHOLAS85** [comment]
Fixed!

**Comment by NICHOLAS85** [comment]
@psprint Just pinging you on this so it doesn't get forgotten

**Comment by psprint** [comment]
Thanks! Merged.

**Pull request merged**
